baseURL = "https://vigilant-euler-ae75f1.netlify.app/"
languageCode = "en-us"
title = "Dr Nick Calvert"
theme = "soho"
enableInlineShortcodes = true

summarylength = 10
enableEmoji = true


[params]
author = "Nick Calvert"
description = "Personal Website"

profilePicture = "images/ProfilePhoto_crop.jpg"

copyright = "Nick Calvert"
license = "CC BY-SA 4.0"
licenseURL = "https://creativecommons.org/licenses/by-sa/4.0"

## Set custom theme color.
themeColor = "#900C3F"

## Set custom CSS and/or JS to override site defaults.
customCss = ["css/blog.css"]
customJs = ["js/blog.js"]

  ## Set as many as you want.

  [[params.socialIcons]]
  icon = "fa-github"
  title = "GitHub"
  url = "https://github.com/ncalvertuk"

  [[params.socialIcons]]
  icon = "fa-linkedin"
  title = "Linkedin"
  url = "https://www.linkedin.com/in/nickcalvert/"

 

  [menu]

  [[menu.main]]
  name = "Posts"
  weight = 100
  identifier = "posts"
  url = "/posts/"

    [[menu.main]]
  name = "CV"
  weight = 100
  identifier = "cv"
  url = "/cv/cv.pdf"

  [[menu.main]]
  name = "About"
  identifier = "about"
  weight = 300
  url = "/about/"




[markup]

  [markup.highlight]
  codeFences = true
  guessSyntax = false
  hl_Lines = ""
  lineNoStart = 1
  lineNos = false
  lineNumbersInTable = true
  noClasses = true # if false, you need to provide you own custom CSS
  style = "monokai"
  tabWidth = 4
  [minify]
disableHTML = false